from typing import Any, Optional
from pydantic import BaseModel, Field

from app.trust.models import TrustReport


class QueryRequest(BaseModel):
    """Payload for submitting a civic inquiry."""

    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="Natural language civic inquiry to be answered with evidence.",
        examples=["What was the total expenditure for Parks & Rec in 2023?"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session tracking identifier for multi-turn inquiry.",
    )
    include_citations: bool = Field(
        default=True,
        description="Whether to retrieve vector document citations.",
    )
    include_calculations: bool = Field(
        default=True,
        description="Whether to execute DuckDB SQL calculations if relevant.",
    )


class CitationItem(BaseModel):
    """Verifiable source excerpt from a vector-indexed municipal document."""

    document_title: str = Field(..., description="Document source title")
    page_number: int = Field(..., description="1-indexed document page number")
    similarity_score: float = Field(..., description="Cosine similarity score (0.0 - 1.0)")
    excerpt: str = Field(..., description="Verbatim matched text excerpt")
    chunk_id: str = Field(..., description="Vector store chunk identifier")
    department: Optional[str] = Field(default=None, description="Department attribution")


class CalculationItem(BaseModel):
    """Verifiable arithmetic derivation executed by the DuckDB analytical engine."""

    query: str = Field(..., description="Exact SQL query executed against DuckDB")
    execution_time_ms: float = Field(..., description="Query latency in milliseconds")
    rows_scanned: int = Field(..., description="Number of table rows scanned")
    table_name: str = Field(..., description="Target database table")
    raw_rows: list[dict[str, Any]] = Field(
        default_factory=list, description="Direct rows returned by DuckDB SQL"
    )
    derivation: str = Field(..., description="Human-readable mathematical derivation")


class QueryResponse(BaseModel):
    """Response payload for an evidence-grounded civic query."""

    query_id: str = Field(..., description="Unique query execution identifier")
    question: str = Field(..., description="Original submitted question")
    answer: str = Field(..., description="Synthesized, evidence-grounded answer")
    citations: list[CitationItem] = Field(
        default_factory=list,
        description="Source document citations backing the answer",
    )
    calculation: Optional[CalculationItem] = Field(
        default=None,
        description="DuckDB SQL calculation trace if quantitative derivation was performed",
    )
    latency_ms: float = Field(default=0.0, description="End-to-end processing latency")
    is_placeholder: bool = Field(
        default=True,
        description="Indicates whether this response was generated by a Stage 3 placeholder service",
    )
    status: str = Field(
        default="completed", description="Execution status of the query pipeline"
    )
    trust: Optional[TrustReport] = Field(
        default=None,
        description="Structured Trust Layer report providing transparent evidence provenance",
    )
